# Generated by Django 4.0.4 on 2022-07-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id de la comuna')),
                ('comName', models.CharField(max_length=50, verbose_name='Nombre de la comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zonaId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id de la zona')),
                ('zonaName', models.CharField(max_length=50, verbose_name='Nombre de la zona')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('traPatent', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente del Transfer')),
                ('traMarca', models.CharField(max_length=50, verbose_name='Marca del Transfer')),
                ('traTamanio', models.CharField(max_length=25, verbose_name='Tamaño del Transfer')),
                ('traDriver', models.CharField(max_length=50, verbose_name='Nombre del Chofer')),
                ('traSeats', models.IntegerField(verbose_name='Cantidad Asientos del Transfer')),
                ('traZona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedirTransfer.zona')),
            ],
        ),
        migrations.CreateModel(
            name='datosPasajero',
            fields=[
                ('paId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id de datos del pasajero')),
                ('paCiudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('paDireccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('paComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedirTransfer.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='Zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedirTransfer.zona'),
        ),
    ]
