# Generated by Django 4.0.4 on 2022-07-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedirTransfer', '0002_alter_datospasajero_paciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospasajero',
            name='paCiudad',
            field=models.CharField(max_length=50, verbose_name='Ciudad'),
        ),
    ]
