# Generated by Django 4.0.4 on 2022-07-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedirTransfer', '0004_datospasajero_paseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='traParking',
            field=models.CharField(default='---', max_length=50, verbose_name='Estacionamiento del transfer'),
        ),
    ]
